version: '3.1'
services:
  redis:
    image: redis
    container_name: my_redis
    restart: always
    command: redis-server --requirepass 123456
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
