# mqtt server
version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_mqtt
    hostname: rabbitmq
    ports: 
      - 1883:1883
      - 5672:5672
      - 15672:15672 
    restart: always
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./etc/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./log:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456 
    networks:
      - lacia
networks:
  lacia:
    external: true
